import pandas as pd
import pdb

foo = [{'red_fighter_name': [['WILLIAM GOMIS']], 'blue_fighter_name': [['OANDERSON BRITO']], 'date': [['09/28/2024']], 'red_fighter_total_pts': [['29', '28', '29']], 'blue_fighter_total_pts': [['28', '29', '28']]}, {'red_fighter_name': [['CHRIS CURTIS']], 'blue_fighter_name': [['KELVIN GASTELUM']], 'date': [['04/08/2023']], 'red_fighter_total_pts': [['28', '27', '28']], 'blue_fighter_total_pts': [['29', '30', '29']]}, {'red_fighter_name': [['CHARLES JOURDAIN']], 'blue_fighter_name': [['ANDRE EWELL']], 'date': [['12/18/2021']], 'red_fighter_total_pts': [['30', '30', '29']], 'blue_fighter_total_pts': [['27', '26', '27']]}, {'red_fighter_name': [['REITSURUYA']], 'blue_fighter_name': [['CARLOS HERNANDEZ']], 'date': [['06/29/2024']], 'red_fighter_total_pts': [['29', '29', '29']], 'blue_fighter_total_pts': [['28', '28', '28']]}, {'red_fighter_name': [['DANIELZELLHUBER']], 'blue_fighter_name': [['ESTEBAN RIBOVICS']], 'date': [['09/14/2024']], 'red_fighter_total_pts': [['28', '29', '28']], 'blue_fighter_total_pts': [['29', '28', '29']]}, {'red_fighter_name': [['TREVIN GILES']], 'blue_fighter_name': [['PRESTON PARSONS']], 'date': [['03/25/2023']], 'red_fighter_total_pts': [['29', '28', '29']], 'blue_fighter_total_pts': [['28', '29', '28']]}, {'red_fighter_name': [['LUIS SALDANA']], 'blue_fighter_name': [['BRUNO SOUZA']], 'date': [['03/26/2022']], 'red_fighter_total_pts': [['29', '29', '29']], 'blue_fighter_total_pts': [['28', '28', '28']]}, {'red_fighter_name': [['BRYAN BARBERENA']], 'blue_fighter_name': [['DARIAN WEEKS']], 'date': [['12/04/2021']], 'red_fighter_total_pts': [['29', '29', '29']], 'blue_fighter_total_pts': [['28', '28', '28']]}, {'red_fighter_name': [['JORDAN WRIGHT']], 'blue_fighter_name': [['BRUNO SILVA']], 'date': [['12/11/2021']], 'red_fighter_total_pts': [['-', '-', '-']], 'blue_fighter_total_pts': [['-', '-', '-']]}, {'red_fighter_name': [['MARC DIAKIESE']], 'blue_fighter_name': [['VIACHESLAVBORSHCHEV']], 'date': [['03/26/2022']], 'red_fighter_total_pts': [['30', '30', '30']], 'blue_fighter_total_pts': [['27', '27', '27']]}]

results = {"red_fighter_name": [entry["red_fighter_name"][0][0] for entry in foo],
               "blue_fighter_name": [entry["blue_fighter_name"][0][0] for entry in foo],
               "date": [entry["date"][0][0] for entry in foo],
               "red_fighter_total_pts": [entry["red_fighter_total_pts"][0] for entry in foo],
               "blue_fighter_total_pts": [entry["blue_fighter_total_pts"][0] for entry in foo]}

bar = pd.DataFrame(results)
print(bar)